Release 5 (#141)
* update: readme
* remove: unused code
* update: readme
* update(sdl2): android
* improve(cmake): rpath (#96)
* fix(android): dlopen failed: library libfreetype.so not found (#97)
* fix(android): Failed to convert UTF8 text (#98)
* Revert "fix(android): Failed to convert UTF8 text (#98)"
* update: readme
* improve(file-picker): add filter option on linux (#99)
* improve(file-picker): add filter option on macos (#100)
* add: file-picker on android (#101)
* add: file-picker on ios (#102)
* update(cmake): remove freetype dependency
* update(cmake): add static freetype dependency on ios
* fix(android/gradlew): Permission denied
* update: readme
* add: file-picker on ios (#102)
* improve(table): send column resize event when resetting width by double-clicking (#103)
* improve(pagination): send event when navigating list/table pages (#104)
* improve(file-picker): allow selecting a large amount of files on windows (#105)
* improve(scroll): send event using the mouse wheel (#106)
* improve(scroll): don't apply offsets if scroll bar is disabled (#107)
* fix(text-color): apply change to sub-components (#108)
* add(text): endpoint to set font style (#109)
* improve(scroll): don't apply offsets if scroll bar is disabled (#107)
* add(api): endpoints to set width/height in percent (#110)
* improve(spacing): only add when component has more than 1 sub-component (#111)
* improve(optimization): add api option to skip re-calculating entire layout per call (#112)
* improve(list): ignore negative row values on remove (#113)
* improve(spacing): only add when component has more than 1 sub-component (#111)
* improve(image): downscaling (#114)
* add: mobile-friendly list (tiles) (#14)
* update: version
* improve(tiles): update selection after setting/removing items (#115)
* add(tiles): get/set scroll api methods (#116)
* improve(tiles): use full image height when no text is set (#117)
* fix(tiles): integer division by 0 (getTilesPerRow returns 0) (#118)
* improve(image): allow empty file values (#120)
* improve(modal): title clipping (#121)
* improve(image): scaling and rotation (#122)
* add(api): method to extract exif data from images (#123)
* add(api): methods to set buttons in a panel (#119)
* fix(tiles): memory leak when replacing items (#124)
* improve(ui): cache loaded color themes (#125)
* improve(events): increase double-click time (#126)
* add(xml): navigation component (#127)
* fix(tiles): don't trigger activation when double-clicking background area (#128)
* add: toggle switch (#31)
* improve(navigation): change cursor when hovering active arrows (#129)
* add(exif): gps tags (#130)
* fix(exif): clean up resources on close (#131)
* improve(list/table): don't auto-select first row when setting items (#132)
* improve(modal): change cursor on hoverable sub-components (#133)
* add(sdl2_image): tiff and webp (#134)
* fix(build): error: format is not a member of std (#136)
* fix(build): to_chars is unavailable: introduced in ios 16.5 and macos 13.4 (#137)
* fix(build): linker errors for webp on ios (#138)
* update(doc): min compiler version for cpp 20
* update(build): library versions
* update: readme
* fix(android): sdl version mismatch (#139)
* update(doc): screenshots
* update(build): license file name
* improve(build): LSG_EXT_LIB_DIR (#140)