Release 6 (#197)
* fix(build): rpath on linux and macosx (#196)
* fix(openmp): crashes on macos (#195) - replace openmp with thread and latch
* fix(border-radius): slider thumb is not dpi-scaled (#194)
* fix(scroll-bar): rounded texture cache is not reset when content of list/table/cards/tiles is updated (#193)
* add(api): LSG_RenderTextureWithRoundedCorners (#192)
* fix(border-radius): text background does not match image (#191)
* fix(progress-bar): rounded progress not filled if initial value is 0 (#190)
* fix(test): color theme not selected in menu on init (#189)
* fix(border-radius): custom radius for icons in menu, modal and text input (#188)
* fix(font): arial unicode has been removed in windows 11 (#187)
* fix(ui): scrollable textures can become bigger than max allowed by renderer (#185)
* fix(menu): items not always rendered properly on mobile (#184)
* fix(android): libomp (#183)
* add: rounded borders (#182)
* fix(ios): dpi scaling (#180)
* improve(cards+tiles): create surfaces in parallel (#179)
* fix(modal): do not close when clicking on backdrop if close-icon is hidden (#178)
* chore(dependencies): update to latest version (#177)
* fix(button): clipping when rendering both text and icon (#176)
* improve(cards+tiles): create surfaces and textures in parallel (#175)
* improve(exif): add support for parallel executions (#174)
* fix(render): components inside modal (#173)
* fix(surface): race condition between cards and main thread (#172)
* improve(tiles): create surfaces in a separate thread (#171)
* improve(cards): create surfaces in a separate thread (#170)
* add(api): LSG_OpenMenu (#169)
* fix(ui): GetFillArea must calculate even when border is 0 (#168)
* improve(rendering): force ui layout on device/target reset (#167)
* add(api): LSG_GetScroll* for Cards (#166)
* fix(cards): use border color on select and highlight (#164)
* add(api): LSG_Scroll* for Cards (#163)
* add(api): LSG_SelectCardRowByOffset (#162)
* add(api): LSG_GetCardsCount (#161)
* add(api): LSG_GetImageThumbnail from SDL_Surface* (#160)
* fix(render): components inside scrollable panel (#159)
* add(ui): mobile-friendly list - cards (#158)
* add(text): LSG_GetFontStyle (#157)
* improve(android): update package path (#156)
* fix(ui): LSG_SelectRowByOffset does not scroll vertically (#155)
* fix(menu): items take up space when not vsiible (#154)
* improve(window): remove min size by default (#153)
* fix(events): remove mobile event filtering (#151)
* improve(ui): don't render wrapping text and tiles if there's not enough height to display first row (#150)
* improve(navigation): dpi scale arrow size (#149)
* update(build): rpath on macosx (#148)
* improve(text): replace custom format with std::format (#147)
* fix(build): static dependencies on ios (#146)
* fix(build): only copy existing licenses to dist (#145)
* update(docs): dependencies (#144)
* fix(build): undefined reference to hb_ft_face_create on linux (#143)
* improve(build): install licenses without creating directory structure (#142)